name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME || 'zoyopei/test' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: echo ${{ steps.branch-names.outputs.current_branch }}

    #- name: Build and push
    #  uses: docker/build-push-action@v6
    #  with:
    #    platforms: linux/amd64,linux/arm64
    #    push: true
